### ISSUE TITLE
Typing & entering a value which is not part of Multivalue control Extension freeze the field.

### ISSUE THREAD

**Issue by GauravBatraTR** [microsoft/vsts-extension-multivalue-control#272] opened 2023-09-14 10:35 UTC
It is observed that whenever a user feeds in any value in Multivalue control Extension field (conditon #1: which is not part of the existing list of values and condition #2: 'Allow users to enter custom values' is checked out) freeze the said field completely and moreover the feed in value is not visible to the user.

The user has no option but to refresh the page as make the said field in working state again to put the correct value.

Steps to Reproduce.
1. Consider the Multi value control extension field named "Choice" is already set with values like Yes, No, May Be. Also 'Allow users to enter custom values' is checked out at setting page.
2. On UI, try typing "Yesssssss" and hit Enter key.
3. Observe that the field "Choice" get freeze and the value "Yesssssss" is also not visible.
4. Now try to add another value using any existing value. 
5. User is unable to do so until the user refreshes the page.

Screenshot is attached here for reference.![multi value control extension field freeze issue](https://github.com/microsoft/vsts-extension-multivalue-control/assets/91320655/9a32e6d2-3859-423d-94a0-a7f9d4d8b27c)

**Comment by AminTi** [comment] 2023-09-25 11:10
Thanks for reporting, we'll dig into this.

**Comment by GauravBatraTR** [comment] 2023-09-25 11:59
Hi @AminTi - Any ETA on this?

**Comment by GauravBatraTR** [comment] 2023-09-25 12:00
> Thanks for reporting, we'll dig into this.

Hi @AminTi  - Any ETA on this?

**Comment by GauravBatraTR** [comment] 2023-10-18 14:31
Hi @AminTi - It's been over a month, there no progress/update on this bug on when it will be fixed?
Thanks.

**Comment by AminTi** [comment] 2023-10-19 11:12
Hi!, I couldn't reproduce this issue. Can we set up a web session?

**Comment by AminTi** [comment] 2023-10-25 11:46
If you continue to experience the same issue, please inform me.

**Comment by GauravBatraTR** [comment] 2023-10-25 11:50
Hi @AminTi,
Yes the team has confirmed that they are still able to replicate it.
Share me your email id and the convenient time (per IST) so that I could setup a session accordingly.

Thanks.

**Comment by AminTi** [comment] 2023-10-26 11:13
amin.titi@solidify.dev

**Comment by AminTi** [comment] 2023-11-16 13:34
@GauravBatraTR  I have been working on other extensions and will prioritize this issue as soon as possible.

**Comment by AminTi** [comment] 2023-12-07 10:59
Hello @GauravBatraTR, I've been dedicating my attention to another extension, but I assure you I'll prioritize this issue as soon as possible. Unfortunately, I couldn't afford the time just yet. Thanks for your patience and understanding.

**Comment by f16hari** [comment] 2024-02-24 13:51
@GauravBatraTR,
Sorry late to the party here, I can spend some time to fix this. But unfortunately not able to replicate could you elaborate when exactly is it reproducible. I know you might had a discussion on this with @AminTi, but documenting here again would really help

**Comment by AminTi** [comment] 2024-02-25 20:34
I've been focusing on another project recently, but I want to assure you that I haven't forgotten about this issue. I'll make it a priority to fix it as soon as possible. Thank you for your patience and understanding.

**Comment by GauravBatraTR** [comment] 2024-02-26 08:21
Hi @f16hari - The steps to reproduce are mentioned in the description. Moreover, I and the respective team member (who identified this issue) had explained and showcase the issue to @AminTi in October 2023 over a call.

Today, I and the person who identified this issue have verified it on Taks, Bug and Product Backlog Item work item types and it seems fixed (perhaps in any interim release).

You may close this ticket.
Thanks.

**Comment by AminTi** [comment] 2024-03-16 13:53
I will close this issue. If you encounter the same problem again, please inform us.

**Closed by AminTi** 2024-03-16 13:53 UTC
Labels: bug, help wanted
