### ISSUE TITLE
New Boards Hub is breaking the extension

### ISSUE THREAD

**Issue by twillliams** [microsoft/vsts-extension-multivalue-control#273] opened 2023-10-05 15:09 UTC
When the New Boards Hub is turned on, the multivalue extension is not rendering on work items.

**Comment by AminTi** [comment] 2023-10-09 07:19
Hi, thanks for reporting, it will be fixed in an upcoming release.

**Comment by twillliams** [comment] 2023-10-10 16:21
Hello,

We have availability on the following times (EST):

Wed 10/11:  11:00 am and 3:00 pm
Thursday 10/12:  2:00 pm, 3:00 – 4:30 pm

Thank you,


Toya Williams  (she/her/hers)
Senior Manager, Tools and Innovation
Applications Development

M   +1(704) 674-8484
[Logo  Description automatically generated]

**Comment by twillliams** [comment] 2023-10-11 14:35
https://github.com/microsoft/vsts-extension-multivalue-control/assets/84200641/624e44e1-4a27-4492-bcca-399b221b090d

**Comment by twillliams** [comment] 2023-10-11 14:35
https://github.com/microsoft/vsts-extension-multivalue-control/assets/84200641/fba2aa90-d27b-49de-a316-3098f6f91054

**Comment by AminTi** [comment] 2023-10-12 09:31
Hi, can you check if you get any errors in the browser console or network log?
you can add me on Teams so that we can schedule a meeting? If I cannot reproduce it, we can discuss the issue further.
amin.titi@solidify.dev

**Comment by twillliams** [comment] 2023-10-12 18:16
Hello,

I can add you on teams.  We have tried several options to fix it, it is still not working.



Toya Williams  (she/her/hers)
Senior Manager, Tools and Innovation
Applications Development

M   +1(704) 674-8484
[Logo  Description automatically generated]

**Comment by brandonmartinez** [comment] 2023-10-16 18:23
I'm experiencing this issue as well. To reproduce, enable the "new boards hub" feature, then navigate to a backlog. Open the item in pop up view, and the control does not render. If you go to the dedicated page view of the work item, it works as expected. Disabled "new boards hub" fixes the normal pop up view.

**Comment by AminTi** [comment] 2023-10-19 10:40
Hello, I couldn't replicate the problem. If you're still experiencing the same issue, please reach out to me on Teams at [amin.titi@solidify.dev](mailto:amin.titi@solidify.dev.

**Closed by AminTi** 2023-10-19 10:40 UTC
